version: '3.6'

services:
  mysql:
    image: mysql
    container_name: craftbase_mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    ports:
      - 3306:3306

#docker volume create craftbase_mysql_data
volumes:
  mysql_data:
    external:
      name: craftbase_mysql_data

#docker network create craftbase_network
networks:
  default:
    external:
      name: craftbase_network