name: Run Build After Each Merge To Master

on:
  repository_dispatch:
    types: run-build
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: my-secret-pw
        ports:
          - 4306:3306

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache gradle dependencies
        uses: actions/cache@v1
        with:
          path: .gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/dependencies.gradle') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Build
        run: ./gradlew clean build -PrunningOnCI=true
        env:
          GRADLE_USER_HOME: .gradle/

